/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectgui;

import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Naufal D~A
 */
public class Home_page extends javax.swing.JFrame {

    /**
     * Creates new form Home_page
     */
    public Home_page() {
        initComponents();
        setLocationRelativeTo(null);
        name_label.setText(Register_page.name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePage_panel = new javax.swing.JPanel();
        minimize_ = new javax.swing.JLabel();
        close_ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameMahasiswa_textField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nim_textField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nilaiTugas_textField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nilaiKuis_textField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nilaiUTS_textField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nilaiUAS_textField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        rataRataLabel = new javax.swing.JLabel();
        keteranganLabel = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        hitung_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        simpan_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(725, 440));
        setUndecorated(true);
        getContentPane().setLayout(null);

        homePage_panel.setBackground(new java.awt.Color(31, 29, 43));
        homePage_panel.setMinimumSize(new java.awt.Dimension(725, 460));
        homePage_panel.setPreferredSize(new java.awt.Dimension(725, 460));

        minimize_.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        minimize_.setForeground(new java.awt.Color(241, 240, 242));
        minimize_.setText("-");
        minimize_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_MouseClicked(evt);
            }
        });

        close_.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        close_.setForeground(new java.awt.Color(241, 240, 242));
        close_.setText("X");
        close_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 240, 242));
        jLabel1.setText("Welcome,");

        name_label.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        name_label.setForeground(new java.awt.Color(241, 240, 242));
        name_label.setText("name");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 240, 242));
        jLabel3.setText("Aplikasi Menghitung Nilai Mahasiswa");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 240, 242));
        jLabel4.setText("Nama");

        nameMahasiswa_textField.setBackground(new java.awt.Color(43, 41, 55));
        nameMahasiswa_textField.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nameMahasiswa_textField.setForeground(new java.awt.Color(241, 240, 242));
        nameMahasiswa_textField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 240, 242));
        jLabel5.setText("NIM ");

        nim_textField1.setBackground(new java.awt.Color(43, 41, 55));
        nim_textField1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nim_textField1.setForeground(new java.awt.Color(241, 240, 242));
        nim_textField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 240, 242));
        jLabel6.setText("Nilai Tugas");

        nilaiTugas_textField2.setBackground(new java.awt.Color(43, 41, 55));
        nilaiTugas_textField2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nilaiTugas_textField2.setForeground(new java.awt.Color(241, 240, 242));
        nilaiTugas_textField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(241, 240, 242));
        jLabel7.setText("Nilai Kuis");

        nilaiKuis_textField3.setBackground(new java.awt.Color(43, 41, 55));
        nilaiKuis_textField3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nilaiKuis_textField3.setForeground(new java.awt.Color(241, 240, 242));
        nilaiKuis_textField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(241, 240, 242));
        jLabel8.setText("Nilai UTS");

        nilaiUTS_textField4.setBackground(new java.awt.Color(43, 41, 55));
        nilaiUTS_textField4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nilaiUTS_textField4.setForeground(new java.awt.Color(241, 240, 242));
        nilaiUTS_textField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(241, 240, 242));
        jLabel9.setText("Nilai UAS");

        nilaiUAS_textField5.setBackground(new java.awt.Color(43, 41, 55));
        nilaiUAS_textField5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        nilaiUAS_textField5.setForeground(new java.awt.Color(241, 240, 242));
        nilaiUAS_textField5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(241, 240, 242));
        jLabel10.setText("Nama");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(241, 240, 242));
        jLabel11.setText("NIM");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(241, 240, 242));
        jLabel12.setText("Grade");

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(241, 240, 242));
        jLabel13.setText("Rata - rata");

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(241, 240, 242));
        jLabel14.setText("Keterangan");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(241, 240, 242));
        jLabel16.setText(":");

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(241, 240, 242));
        jLabel17.setText(":");

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(241, 240, 242));
        jLabel18.setText(":");

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(241, 240, 242));
        jLabel19.setText(":");

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(241, 240, 242));
        jLabel20.setText(":");

        nimLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        nimLabel.setForeground(new java.awt.Color(241, 240, 242));

        namaLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(241, 240, 242));

        rataRataLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        rataRataLabel.setForeground(new java.awt.Color(241, 240, 242));

        keteranganLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        keteranganLabel.setForeground(new java.awt.Color(241, 240, 242));

        gradeLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(241, 240, 242));

        hitung_button.setBackground(new java.awt.Color(108, 94, 207));
        hitung_button.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        hitung_button.setForeground(new java.awt.Color(241, 240, 242));
        hitung_button.setText("Hitung");
        hitung_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hitung_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_buttonActionPerformed(evt);
            }
        });

        reset_button.setBackground(new java.awt.Color(108, 94, 207));
        reset_button.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        reset_button.setForeground(new java.awt.Color(241, 240, 242));
        reset_button.setText("Reset");
        reset_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        simpan_button.setBackground(new java.awt.Color(108, 94, 207));
        simpan_button.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        simpan_button.setForeground(new java.awt.Color(241, 240, 242));
        simpan_button.setText("Simpan");
        simpan_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        simpan_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePage_panelLayout = new javax.swing.GroupLayout(homePage_panel);
        homePage_panel.setLayout(homePage_panelLayout);
        homePage_panelLayout.setHorizontalGroup(
            homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePage_panelLayout.createSequentialGroup()
                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePage_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(name_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimize_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close_))
                    .addGroup(homePage_panelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(homePage_panelLayout.createSequentialGroup()
                                        .addComponent(nameMahasiswa_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addGroup(homePage_panelLayout.createSequentialGroup()
                                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(nilaiKuis_textField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                    .addComponent(nilaiTugas_textField2, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nim_textField1, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13)))
                                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                                .addComponent(nilaiUTS_textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14))
                                            .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(homePage_panelLayout.createSequentialGroup()
                                                    .addComponent(hitung_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(nilaiUAS_textField5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(rataRataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel16))
                                                .addGap(18, 18, 18)
                                                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(nimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                    .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(18, 18, 18)
                                                .addComponent(keteranganLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(18, 18, 18)
                                                .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePage_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(165, 165, 165))
            .addGroup(homePage_panelLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(simpan_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePage_panelLayout.setVerticalGroup(
            homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePage_panelLayout.createSequentialGroup()
                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePage_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(close_)
                            .addComponent(minimize_)))
                    .addGroup(homePage_panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(name_label))))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePage_panelLayout.createSequentialGroup()
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePage_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(nameMahasiswa_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePage_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(nim_textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel17))
                            .addComponent(nimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(nilaiTugas_textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel18))
                            .addComponent(rataRataLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nilaiKuis_textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel19)))
                    .addGroup(homePage_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gradeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePage_panelLayout.createSequentialGroup()
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nilaiUTS_textField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(nilaiUAS_textField5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(homePage_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hitung_button)
                            .addComponent(reset_button)))
                    .addComponent(keteranganLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(simpan_button)
                .addGap(33, 33, 33))
        );

        getContentPane().add(homePage_panel);
        homePage_panel.setBounds(0, 0, 725, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_reset_buttonActionPerformed
        // TODO add your handling code here:
        // Untuk Mereset Halaman
        nameMahasiswa_textField.setText(null);
        nim_textField1.setText(null);
        nilaiTugas_textField2.setText(null);
        nilaiKuis_textField3.setText(null);
        nilaiUTS_textField4.setText(null);
        nilaiUAS_textField5.setText(null);
        namaLabel.setText(null);
        nimLabel.setText(null);
        rataRataLabel.setText(null);
        gradeLabel.setText(null);
        keteranganLabel.setText(null);
    }// GEN-LAST:event_reset_buttonActionPerformed

    private void hitung_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hitung_buttonActionPerformed
        // TODO add your handling code here:
        // Untuk Rata Rata Nilai Mahasiswa
        String nameMahasiswa = nameMahasiswa_textField.getText();
        String nim = nim_textField1.getText();
        if (nilaiTugas_textField2.getText().isEmpty() || nilaiKuis_textField3.getText().isEmpty()
                || nilaiUTS_textField4.getText().isEmpty() || nilaiUAS_textField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Maaf, ada form yang masih kosong");
        } else {
            Double rata_rata = (Double.parseDouble(nilaiTugas_textField2.getText())
                    + Double.parseDouble(nilaiKuis_textField3.getText())
                    + Double.parseDouble(nilaiUTS_textField4.getText())
                    + Double.parseDouble(nilaiUAS_textField5.getText())) / 4;
            rataRataLabel.setText(rata_rata.toString());
            namaLabel.setText(nameMahasiswa);
            nimLabel.setText(nim);
        }

        // Untuk Memberikan Grade dari Rata Rata Nilai Mahasiswa

        double g = Double.parseDouble(rataRataLabel.getText());
        String grade = " ";

        if (g > 80.00) {
            grade = "A";
            gradeLabel.setText("" + grade);
        } else if (g > 70.00 && g <= 80.00) {
            grade = "AB";
            gradeLabel.setText("" + grade);
        } else if (g > 65.00 && g <= 70.00) {
            grade = "B";
            gradeLabel.setText("" + grade);
        } else if (g > 60.00 && g <= 65.00) {
            grade = "BC";
            gradeLabel.setText("" + grade);
        } else if (g > 50.00 && g <= 60.00) {
            grade = "C";
            gradeLabel.setText("" + grade);
        } else if (g > 40.00 && g <= 50.00) {
            grade = "D";
            gradeLabel.setText("" + grade);
        } else if (g <= 40.00) {
            grade = "E";
            gradeLabel.setText("" + grade);
        }

        // Untuk Memberikan Keterangan dari Grade yang Didapatkan

        if ((grade == "A") || (grade == "AB") || (grade == "B") || (grade == "BC") || (grade == "C")) {

            keteranganLabel.setText("Lulus");
        } else {
            keteranganLabel.setText("Tidak Lulus");
        }
    }// GEN-LAST:event_hitung_buttonActionPerformed

    private void close_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_close_MouseClicked
        // TODO add your handling code here:
        // Untuk Close Halaman
        System.exit(0);
    }// GEN-LAST:event_close_MouseClicked

    private void minimize_MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_minimize_MouseClicked
        // TODO add your handling code here:
        // Untuk Minimize Halaman
        this.setState(1);
    }// GEN-LAST:event_minimize_MouseClicked

    private void simpan_buttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_simpan_buttonActionPerformed
        // TODO add your handling code here:
        // Untuk Menyimpan Data dari Nilai yang Telah di Inputkan
        try {
            BufferedWriter wr = new BufferedWriter(new FileWriter("Inputan Nilai Data Mahasiswa.txt", true));
            String data = "Nama \t\t:\t" + nameMahasiswa_textField.getText() + "\n" +
                    "Nim \t\t:\t" + nim_textField1.getText() + "\n" +
                    "Rata-rata \t:\t" + rataRataLabel.getText() + "\n" +
                    "Grade \t\t:\t" + gradeLabel.getText() + "\n" +
                    "Keterangan \t:\t" + keteranganLabel.getText() + "\n\n";
            wr.write(data);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            wr.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }// GEN-LAST:event_simpan_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JButton hitung_button;
    private javax.swing.JPanel homePage_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel keteranganLabel;
    private javax.swing.JLabel minimize_;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField nameMahasiswa_textField;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField nilaiKuis_textField3;
    private javax.swing.JTextField nilaiTugas_textField2;
    private javax.swing.JTextField nilaiUAS_textField5;
    private javax.swing.JTextField nilaiUTS_textField4;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nim_textField1;
    private javax.swing.JLabel rataRataLabel;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton simpan_button;
    // End of variables declaration//GEN-END:variables
}
