/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectgui;

import java.awt.Dimension;

/**
 *
 * @author Naufal D~A
 */
public class Register_page extends javax.swing.JFrame {

    /**
     * Creates new form Register_page
     */
    public static String name;
    public static String username;
    public static String password;

    public Register_page() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register_panel = new javax.swing.JPanel();
        minimize_ = new javax.swing.JLabel();
        close_ = new javax.swing.JLabel();
        signupLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        name_textField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        username_textField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        password_textField = new javax.swing.JPasswordField();
        confirmPassword_label = new javax.swing.JLabel();
        confirmPassword_textField = new javax.swing.JPasswordField();
        warningLabel1 = new javax.swing.JLabel();
        signup_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(360, 440));
        setUndecorated(true);
        getContentPane().setLayout(null);

        register_panel.setBackground(new java.awt.Color(31, 29, 43));
        register_panel.setMaximumSize(new java.awt.Dimension(360, 440));
        register_panel.setPreferredSize(new java.awt.Dimension(360, 440));

        minimize_.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        minimize_.setForeground(new java.awt.Color(241, 240, 242));
        minimize_.setText("-");
        minimize_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_MouseClicked(evt);
            }
        });

        close_.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        close_.setForeground(new java.awt.Color(241, 240, 242));
        close_.setText("X");
        close_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_MouseClicked(evt);
            }
        });

        signupLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        signupLabel.setForeground(new java.awt.Color(241, 240, 242));
        signupLabel.setText("Sign Up");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 79, 94));
        jLabel2.setText("Register to Continue");

        nameLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(241, 240, 242));
        nameLabel.setText("Name");

        name_textField.setBackground(new java.awt.Color(43, 41, 55));
        name_textField.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        name_textField.setForeground(new java.awt.Color(241, 240, 242));
        name_textField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        usernameLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(241, 240, 242));
        usernameLabel.setText("Username");

        username_textField.setBackground(new java.awt.Color(43, 41, 55));
        username_textField.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        username_textField.setForeground(new java.awt.Color(241, 240, 242));
        username_textField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        passwordLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(241, 240, 242));
        passwordLabel.setText("Password");

        password_textField.setBackground(new java.awt.Color(43, 41, 55));
        password_textField.setForeground(new java.awt.Color(241, 240, 242));
        password_textField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        confirmPassword_label.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        confirmPassword_label.setForeground(new java.awt.Color(241, 240, 242));
        confirmPassword_label.setText("Confirm Password");

        confirmPassword_textField.setBackground(new java.awt.Color(43, 41, 55));
        confirmPassword_textField.setForeground(new java.awt.Color(241, 240, 242));
        confirmPassword_textField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        warningLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        warningLabel1.setForeground(new java.awt.Color(255, 0, 0));
        warningLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        signup_button.setBackground(new java.awt.Color(108, 94, 207));
        signup_button.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        signup_button.setForeground(new java.awt.Color(241, 240, 242));
        signup_button.setText("Sign Up");
        signup_button.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout register_panelLayout = new javax.swing.GroupLayout(register_panel);
        register_panel.setLayout(register_panelLayout);
        register_panelLayout.setHorizontalGroup(
            register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_panelLayout.createSequentialGroup()
                .addGroup(register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimize_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close_))
                    .addGroup(register_panelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username_textField)
                            .addComponent(signup_button)
                            .addComponent(confirmPassword_label)
                            .addComponent(confirmPassword_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(usernameLabel)
                            .addComponent(passwordLabel)
                            .addComponent(nameLabel)
                            .addComponent(password_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(signupLabel)
                            .addComponent(name_textField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(warningLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        register_panelLayout.setVerticalGroup(
            register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close_)
                    .addComponent(minimize_))
                .addGap(10, 10, 10)
                .addComponent(signupLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmPassword_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPassword_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signup_button)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        warningLabel1.getAccessibleContext().setAccessibleName("warningLabel");

        getContentPane().add(register_panel);
        register_panel.setBounds(0, 0, 360, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_MouseClicked
        // TODO add your handling code here:
        // Untuk Minimize Halaman
        this.setState(1);
    }//GEN-LAST:event_minimize_MouseClicked

    private void close_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_MouseClicked
        // TODO add your handling code here:
        // Untuk Close Halaman
        System.exit(0);
    }//GEN-LAST:event_close_MouseClicked

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        // Untuk Register
        if(password_textField.getText().equals(confirmPassword_textField.getText())){
            name = name_textField.getText();
            username = username_textField.getText();
            password = password_textField.getText();
            
            // ke Halaman Login
            Login_page lg = new Login_page();
            lg.setVisible(true);
            lg.pack();
            this.dispose();
            lg.setMinimumSize(new Dimension (360,440));
            lg.setLocationRelativeTo(null);
            lg.setDefaultCloseOperation(Register_page.EXIT_ON_CLOSE);
        } else {
            warningLabel1.setText("The password doesn't match");
        }
    }//GEN-LAST:event_signup_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_;
    private javax.swing.JLabel confirmPassword_label;
    private javax.swing.JPasswordField confirmPassword_textField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel minimize_;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField name_textField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField password_textField;
    private javax.swing.JPanel register_panel;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JButton signup_button;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField username_textField;
    private javax.swing.JLabel warningLabel1;
    // End of variables declaration//GEN-END:variables
}
